<?php

namespace Omniship\Fancourier;

use Infifni\FanCourierApiClient\Client as Base;
use Infifni\FanCourierApiClient\Request\EndpointInterface;
use Omniship\Fancourier\BaseExtends\GetPdfAwb;

/**
 * @method getPdfAwb(array $params)
 */
class FanClient extends Base
{
    public function instantiate(string $class): EndpointInterface
    {
        if($class == 'GetPdfAwb') {
            return new GetPdfAwb();
        }

        return parent::instantiate($class); // TODO: Change the autogenerated stub
    }
}